const routeConstants = {
  adminUrls: [
    '/login',
    '/ADMIN',
    '/save-design-quotation',
    '/get-design-quotation',
    '/dnbl-pdf',
    '/add-client',
    '/fetch-all-client',
    '/client/tasks',
    '/pre-sales/fetch-all-unassigned-client',
    '/pre-sales/assigned-client',
    '/assign-to-client',
    '/designer/assigned-client',
    '/designer/client-met',
    '/designer/update-client-met',
    '/designer-on-board-clients',
    '/client-profile',
    '/update-client-profile',
    '/on-site-records',
    '/on-site-categories',
    '/boq-furniture-records',
    '/boq-furniture-categories',
    '/boq-modular-records',
    '/boq-modular-categories',
    '/boq-search-furniture',
    '/boq-search-modular',
    '/boq-generate-pdf',
    '/boq-generate-test',
    '/boq-save-data',
    '/boq-get-data',
    '/admin-to-be-assigned',
    '/admin-assigned-not-met',
    '/admin-delayed-proposals',
    '/admin-assignTo-designer',
    '/admin-assignTo-tl',
    '/admin-payment-dues',
    '/admin-new-sign-ups',
    '/admin-all-presales',
    '/admin-all-clients',
    '/designer-all',
    '/team-leader-all',
    '/teamLead-designer-all',
    '/teamLead-to-be-assigned',
    '/teamLead-assigned-not-met',
    '/teamLead-delayed-proposals',
    '/teamLead-payment-dues',
    '/teamLead-new-sign-ups',
    '/register-designer',
    '/register-teamLead',
    '/register-presales',
    '/register-client',
    '/login-client',
    '/forgot-password',
    '/change-password',
    '/products',
    '/all-items-list',
    '/products/filters',
    '/products/add/categoryId'
  ],
  userUrls: [
    '/check-client-req-form', '/fill-client-req-form'
  ]
};

module.exports = routeConstants;
